export const icon = {
  WHITELOGO: require('../assets/images/Logoforwhite2.png'),
  BLACKLOGO: require('../assets/images/Logoforblack2.png'),
  //LOGOMAIN: require('../assets/images/logoMain.png'),
  TOGGLE: require('../assets/images/openMic/icon/menu-white.png'),
  BG_SENDMAIL: require('../assets/images/openMic/bg_mail.png'),
  EMAIL: require('../assets/images/openMic/email.png'),
  EyeShow: require('../assets/images/show.png'),
  EyeClose: require('../assets/images/eyeclose.png'),
  THEATER: require('../assets/images/openMic/Banner.png'),
  PLACEONE: require('../assets/images/openMic/places/1.jpg'),
  PLACETWO: require('../assets/images/openMic/places/2.jpg'),
  MIC: require('../assets/images/openMic/post-img.png'),
  ICON_CLOCK: require('../assets/images/clock.png'),
  ICON_LOCATION: require('../assets/images/location.png'),
  ICON_CONTACT: require('../assets/images/contacts.png'),
  ICON_MIC: require('../assets/images/mic.png'),
  MICTWO: require('../assets/images/mic2.jpg'),
  PROFILE_DEFAULT: require('../assets/images/openMic/User.png'),
};
