const strings = {
  LOGINHEADING: 'Welcome To Login Screen',
  LOGIN: 'LOG IN',
  SIGNUP: 'SIGN UP',
  HOME: 'HOME',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  EMAILREQ: 'Enter Valid Email',
  PASSREQ: 'Enter Password',
  NO_INTERNET_CONNECTION: 'No Internet Connection',
  FORGOT_PASSWORD: 'Forgot Password?',
  SIGNUP_SMALL: 'Sign Up',
  LOGIN_SMALL: 'Login and Post your mic...',
  SIGNUPTEXT:
    'You need an account to edit, manage, and eventually delete your mic when the venue goes out of business.',
  LOGOUT: 'LOGOUT',
  FIRSTNAME: 'First Name *',
  LASTNAME: 'Last Name *',
  EMAILTEXT: 'Email Address *',
  PASSWORDTEXT: 'Password *',
  CONPASSWORDTEXT: 'Confirm Password *',
  CONTACTNO: 'Contact Number *',
  RESENDMAILTEXT:
    'Congratulation! Welcome in Open Mic List.We sent you a link to ',
  RESENDMAILTEXT2: 'Confirm your email address.',
  SENDMAIL: 'RE SEND MAIL',
  FOOTER_SENDMAIL: 'If you never received an email from us, there’s a few places the email may have landed: Please check your Spam, junk, and bulk mail folders: Sometimes our emails are blocked or filtered as spam by certain email providers or internet service providers (ISPs). You may also click the Resend Mail button above.', 
  BTN_REGION: 'Change Region',
  BTN_FILTER: 'Apply Filter',
  REGINTEXT: 'Register and Post your mic...',
  MICTYPE: 'Select Mic Type',
  SEARCHMIC: 'Quick Search',
  BTN_FILTER_APPLY: 'Apply Filter',
  WEEK_DAYS: 'VIEW OTHER WEEK DAYS',
  HIDE_WEEK_DAYS: 'HIDE OTHER WEEK DAYS',
  DASHBOARD: 'DASHBOARD',
  DASHBOARD_LABEL: 'Let’s make laugh everyone',
  DASHBOARD_TAB_ONE: 'Draft',
  DASHBOARD_TAB_TWO: 'My mics',
  DASHBOARD_TAB_THREE: 'Account settings',
  DASHBOARD_TAB_FOUR: 'Interested to participate',
  OLD_PASSWORD: 'Old Password *',
  NEW_PASSWORD: 'New Password *',
  CONFIRM_PASSWORD: 'Confirm Password *',
  CHANGE_PASSWORD: 'Change Password',
  SAVE: 'Save',
  UPDATE_ACCOUNT_DETAILS: 'Update Account Details',
};

export default strings;
